blueprint:
  name: Hobeian ZG-101ZS Zigbee2MQTT
  description: >
    Control remoto Zigbee de 4 botones (ZG-101ZS) con soporte de pulsación simple,
    doble y larga mediante Zigbee2MQTT. Incluye gestión de debounce y acciones repetitivas
    durante la pulsación larga.
  domain: automation
  input:
    remote:
      name: Dispositivo remoto
      description: Entidad del sensor de acciones de Zigbee2MQTT
      selector:
        entity:
          domain: sensor

    helper_last_event:
      name: Helper de último evento
      description: Entidad input_text para registrar el último evento
      selector:
        entity:
          domain: input_text

    debounce_delay:
      name: Retraso de debounce
      description: Tiempo de espera en milisegundos para evitar rebotes
      default: 200
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: ms
          step: 50

    long_loop_delay:
      name: Intervalo de repetición en pulsación larga
      description: Tiempo en milisegundos entre repeticiones durante una pulsación larga
      default: 500
      selector:
        number:
          min: 100
          max: 2000
          unit_of_measurement: ms
          step: 50

    enable_long_actions:
      name: Habilitar acciones largas
      description: Permite que las acciones largas se repitan mientras se mantenga pulsado
      default: true
      selector:
        boolean: {}

    button_1_single:
      name: Botón 1 - Pulsación simple
      default: []
      selector:
        action: {}

    button_1_double:
      name: Botón 1 - Doble clic
      default: []
      selector:
        action: {}

    button_1_long:
      name: Botón 1 - Pulsación larga
      default: []
      selector:
        action: {}

    button_2_single:
      name: Botón 2 - Pulsación simple
      default: []
      selector:
        action: {}

    button_2_double:
      name: Botón 2 - Doble clic
      default: []
      selector:
        action: {}

    button_2_long:
      name: Botón 2 - Pulsación larga
      default: []
      selector:
        action: {}

    button_3_single:
      name: Botón 3 - Pulsación simple
      default: []
      selector:
        action: {}

    button_3_double:
      name: Botón 3 - Doble clic
      default: []
      selector:
        action: {}

    button_3_long:
      name: Botón 3 - Pulsación larga
      default: []
      selector:
        action: {}

    button_4_single:
      name: Botón 4 - Pulsación simple
      default: []
      selector:
        action: {}

    button_4_double:
      name: Botón 4 - Doble clic
      default: []
      selector:
        action: {}

    button_4_long:
      name: Botón 4 - Pulsación larga
      default: []
      selector:
        action: {}

mode: restart

trigger:
  - platform: state
    entity_id: !input remote

variables:
  trigger_action: "{{ trigger.to_state.state }}"
  debounce_delay: !input debounce_delay
  long_loop_delay: !input long_loop_delay
  enable_long_actions: !input enable_long_actions
  helper_last_event: !input helper_last_event

condition:
  - condition: template
    value_template: >
      {{ trigger_action not in ['None','unknown','unavailable',''] }}

action:
  - choose:
      - conditions: "{{ trigger_action == '1_single' }}"
        sequence: !input button_1_single
      - conditions: "{{ trigger_action == '1_double' }}"
        sequence: !input button_1_double
      - conditions: "{{ trigger_action == '1_long' and enable_long_actions }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {{ states(helper_last_event) == '1_long' }}
              sequence:
                - sequence: !input button_1_long
                - delay: "{{ long_loop_delay | int / 1000 }}"

      - conditions: "{{ trigger_action == '2_single' }}"
        sequence: !input button_2_single
      - conditions: "{{ trigger_action == '2_double' }}"
        sequence: !input button_2_double
      - conditions: "{{ trigger_action == '2_long' and enable_long_actions }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {{ states(helper_last_event) == '2_long' }}
              sequence:
                - sequence: !input button_2_long
                - delay: "{{ long_loop_delay | int / 1000 }}"

      - conditions: "{{ trigger_action == '3_single' }}"
        sequence: !input button_3_single
      - conditions: "{{ trigger_action == '3_double' }}"
        sequence: !input button_3_double
      - conditions: "{{ trigger_action == '3_long' and enable_long_actions }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {{ states(helper_last_event) == '3_long' }}
              sequence:
                - sequence: !input button_3_long
                - delay: "{{ long_loop_delay | int / 1000 }}"

      - conditions: "{{ trigger_action == '4_single' }}"
        sequence: !input button_4_single
      - conditions: "{{ trigger_action == '4_double' }}"
        sequence: !input button_4_double
      - conditions: "{{ trigger_action == '4_long' and enable_long_actions }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: >
                    {{ states(helper_last_event) == '4_long' }}
              sequence:
                - sequence: !input button_4_long
                - delay: "{{ long_loop_delay | int / 1000 }}"

  - service: input_text.set_value
    target:
      entity_id: !input helper_last_event
    data:
      value: "{{ trigger_action }}"
